server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8080

# 로그 레벨 설정
logging:
  level:
    root: INFO                 # 모든 라이브러리는 INFO 이상 출력
    com.chakak: DEBUG            # 내 프로젝트는 DEBUG 이상 모두 출력
    org.hibernate.SQL: debug    # Hibernate 실행 쿼리 출력
    org.hibernate.type.descriptor.sql: trace  # 쿼리 파라미터 값 출력

spring:
  config:
    import: optional:application-secret.yml

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: chakak
    password: chakak1234

  # H2 데이터베이스 웹 콘솔 활성화 (개발용)
  h2:
    console:
      settings:
        web-allow-others: true

#  sql:
#     init:
#       mode: always
#       data-locations:
#         - classpath:db/data.sql

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true                # SQL 예쁘게 출력
        default_batch_fetch_size: 10
    defer-datasource-initialization: true

  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

kakao:
  api:
    client-id: ${KAKAO_CLIENT_ID}
    redirect-uri: http://localhost:8080/api/auth/kakao/callback
    token-uri: https://kauth.kakao.com/oauth/token
    user-info-uri: https://kapi.kakao.com/v2/user/me