
server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8080

logging:
  level:
    root: INFO
    com.chakak: DEBUG

spring:
  config:
    import: optional:application-secret.yml

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: chakak
    password: chakak1234

  h2:
    console:
      enabled: true
      path: /h2-console  # 선택적으로 변경 가능

  sql:
    init:
      mode: never
      data-locations:
        - classpath:db/data.sql

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 10
    defer-datasource-initialization: true

    mail:
      host: smtp.gmail.com
      port: 587
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true